TARGET = simpleserial-ascon-keyleak-sanity
PLATFORM = CWLITEXMEGA
CRYPTO_TARGET = NONE
SS_VER = SS_VER_1_1
FIRMWAREPATH = C:/Users/thetp/ChipWhisperer/chipwhisperer/firmware/mcu
SRC += simpleserial-ascon-keyleak-sanity.c
include $(FIRMWAREPATH)/Makefile.inc
